### ISSUE TITLE
scala 3.3 merge broke nightly jar publish (scaladoc issue)

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#157]
see https://github.com/apache/incubator-pekko-http/actions/runs/5090942292/jobs/9151097224

fyi @mdedetrich 

may have another cause but the recent merge is likely candidate

I spotted that some of the build params had 'akka' prefixes earlier (including one related to scaladoc diagrams) and was trying to fix that - may be related to this (#155)

**Comment by mdedetrich** [comment]
@pjfanning Do you want to go ahead and merge https://github.com/apache/incubator-pekko-http/pull/155 then?

**Comment by pjfanning** [comment]
I still haven't had a chance to do a full analysis of this issue but I think #155 is more likely to help than to make things worse

**Comment by mdedetrich** [comment]
Okay well just let me know when you want me to look into this

**Comment by pjfanning** [comment]
@mdedetrich this happens with and without #155 

You can reproduce with `sbt doc`. I don't know why this has started happening now.

**Comment by mdedetrich** [comment]
Okay I will look at it then

**Comment by pjfanning** [comment]
One oddity is in project/Doc.scala. The skip-packages is defined twice. Once without the scala version check and then again with the version check.

**Comment by mdedetrich** [comment]
> Indeed I think I messed up the merge conflict, trying this out now. Its meant to be `org.apache.pekko.pattern`

So this solved one problem, there is however another which I am looking into

**Comment by mdedetrich** [comment]
@pjfanning So this is a bit of a red herring, `sbt doc` doesn't in general work, whether before or after the scala 3 PR. What you are meant to use instead is `sbt unidoc` (the difference between `doc` and `unidoc` is that it `unidoc` merges all of the documentation from different projects/packages which is why `sbt doc` failed).

Nonetheless there was cases of dulicated lines/regressions which I will clean up.
