### ISSUE TITLE
try to avoid shutdown hooks

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#175]
See https://github.com/apache/incubator-pekko-http/pull/170

It is usually better to try to manage the lifecycle of the temp files in code so that they are deleted explicitly in code when they are no longer needed.

It looks like when the PR code above is used, that the code does remove the file explicitly - see https://github.com/apache/incubator-pekko-http/blob/20c3fea9d950d14157438918b8ba8e7747505f71/http/src/main/scala/org/apache/pekko/http/scaladsl/server/directives/FileUploadDirectives.scala#L192

Maybe, we could just remove the shutdown hook.

fyi @mdedetrich

**Comment by mdedetrich** [comment]
Isn't the idea of adding the shutdown hook to take care of the scenario where the process gets interrupted/cancelled after the temp file is created and before https://github.com/apache/incubator-pekko-http/blob/20c3fea9d950d14157438918b8ba8e7747505f71/http/src/main/scala/org/apache/pekko/http/scaladsl/server/directives/FileUploadDirectives.scala#L192 is executed?

Also note that I was replicating the current behaviour, the previous `deleteOnExit()` also adds a shutdown hook, it just doesn't happen to exist on `java.nio.file.Path`. I guess we can get rid of the explicit shutdown hook and just do `dest.toFile.deleteOnExit()` so that its exactly the same as old behaviour (I would just presume that `java.nio.Files.deleteIfExists` is faster)

**Comment by pjfanning** [comment]
@mdedetrich shouldn't this handle failures?

```
FileIO.fromPath(src.toPath)
              .mapMaterializedValue { f =>
                f.onComplete(_ => src.delete())
              }
```

The `mapMaterializedValue` is working `Future[IOResult] => Unit`. `Future#onComplete` works on `Try[IOResult]` so the `src.delete()` happens for Success and Failure.

ShudownHooks
* use memory (what if we have millions of files)
* slow down the shutdown

For me, shutdown hooks are nearly as bad as finalizers.

**Comment by mdedetrich** [comment]
> @mdedetrich shouldn't this handle failures?
> 
> ```
> FileIO.fromPath(src.toPath)
>               .mapMaterializedValue { f =>
>                 f.onComplete(_ => src.delete())
>               }
> ```
> 
> The `mapMaterializedValue` is working `Future[IOResult] => Unit`. `Future#onComplete` works on `Try[IOResult]` so the `src.delete()` happens for Success and Failure.

So there are multiple things going on here, one is the creation of the files and the other is the storing for them. 

> 
> ShudownHooks
> 
> * use memory (what if we have millions of files)
> * slow down the shutdown
> 
> For me, shutdown hooks are nearly as bad as finalizers.

If this was a concern than I presume it would have already been raised because as I said `deleteOnExit()` which is what was there previously also uses shutdown hooks. I did check the source more concretely and it does appear to do it in a more performant way, i.e. it has a single instances of a `ShutdownHook` with a collection of files to be deleted. I will make a PR to just do the `dest.toFile.deleteOnExit`.
