### ISSUE TITLE
fix links to pekko-http snapshot javadoc/scaladoc

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-http#213]
The current nightly builds publish docs but the links to the javadoc/scaladoc from the reference docs uses the full snapshot version. We do not publish to https://nightlies.apache.org/pekko/docs/pekko-http/main-snapshot/ with the full snapshot version.

Example: See `HttpRequest` link in https://pekko.apache.org/docs/pekko-http/current/introduction.html#low-level-http-server-apis

Today that links to https://pekko.apache.org/japi/pekko-http/0.0.0+4453-9a48d9fc-SNAPSHOT/org/apache/pekko/http/scaladsl/model/HttpRequest.html

For snapshot builds, can we change the link just to have `snapshot` instead of the full snapshot version?

So the link above would be https://pekko.apache.org/japi/pekko-http/snapshot/org/apache/pekko/http/scaladsl/model/HttpRequest.html - which works

**Comment by pjfanning** [comment]
fyi @jrudolph @mdedetrich

**Comment by mdedetrich** [comment]
While its true that in Akka's case, for the latest release branch it does maintain different patch versions (i.e. https://doc.akka.io/docs/akka/2.8.1/ vs https://doc.akka.io/docs/akka/2.8.2/) there is also https://doc.akka.io/docs/akka/2.8/ which points to the latest version (i.e. https://doc.akka.io/docs/akka/2.8.2 with my previous example), note that this is **NOT** the same as the docs pointing to the latest point of the 2.8 branch.

So there are 2 ways to solve this problem, one is to find a way so that we can point `1.0` to the latest released version (which will be `1.0.0`) or we do as you suggested and change to using patch versions.

**Comment by pjfanning** [comment]
> While its true that in Akka's case, for the latest release branch it does maintain different patch versions (i.e. https://doc.akka.io/docs/akka/2.8.1/ vs https://doc.akka.io/docs/akka/2.8.2/) there is also https://doc.akka.io/docs/akka/2.8/ which points to the latest version (i.e. https://doc.akka.io/docs/akka/2.8.2 with my previous example), note that this is **NOT** the same as the docs pointing to the latest point of the 2.8 branch.
> 
> So there are 2 ways to solve this problem, one is to find a way so that we can point `1.0` to the latest released version (which will be `1.0.0`) or we do as you suggested and change to using patch versions.

@mdedetrich was this comment intended for https://github.com/apache/incubator-pekko-http/issues/212 ?

**Comment by mdedetrich** [comment]
Yes it was, let me repost it there

**Comment by pjfanning** [comment]
#214 merged
